<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Beauty_Aesthetics_Hybrid.Shared\Beauty_Aesthetics_Hybrid.Shared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="EBIDM">
      <HintPath>..\Beauty_Aesthetics_Hybrid.Shared\Libraries\EBI\EBIDM.dll</HintPath>
    </Reference>
    <Reference Include="EBIEF">
      <HintPath>..\Beauty_Aesthetics_Hybrid.Shared\Libraries\EBI\EBIEF.dll</HintPath>
    </Reference>
    <Reference Include="EBIEnum">
      <HintPath>..\Beauty_Aesthetics_Hybrid.Shared\Libraries\EBI\EBIEnum.dll</HintPath>
    </Reference>
    <Reference Include="EBIUC">
      <HintPath>..\Beauty_Aesthetics_Hybrid.Shared\Libraries\EBI\EBIUC.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
