<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>Beauty_Aesthetics_WebPos</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <SupportedPlatform Include="browser" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.Web" Version="10.0.0" />
    <PackageReference Include="ClosedXML" Version="0.105.0" />
    <PackageReference Include="EPPlus" Version="8.2.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="10.0.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.1" />
    <PackageReference Include="Microsoft.Extensions.Localization" Version="10.0.0" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="EBIDM">
      <HintPath>..\..\..\..\Downloads\EBIDM.dll</HintPath>
    </Reference>
    <Reference Include="EBIEF">
      <HintPath>..\..\..\..\Downloads\EBIEF.dll</HintPath>
    </Reference>
    <Reference Include="EBIEnum">
      <HintPath>..\..\..\..\Downloads\EBIEnum.dll</HintPath>
    </Reference>
    <Reference Include="EBIUC">
      <HintPath>..\..\..\..\Downloads\EBIUC.dll</HintPath>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Libraries\EBI\" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\..\..\..\Downloads\EBIDM.dll" Link="Libraries\EBI\EBIDM.dll" />
    <None Include="..\..\..\..\Downloads\EBIEF.dll" Link="Libraries\EBI\EBIEF.dll" />
    <None Include="..\..\..\..\Downloads\EBIEnum.dll" Link="Libraries\EBI\EBIEnum.dll" />
    <None Include="..\..\..\..\Downloads\EBIUC.dll" Link="Libraries\EBI\EBIUC.dll" />
  </ItemGroup>

</Project>
